name: Build and Push Docker Image and Binaries

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install Protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Run Tests
        run: make test

      - name: Generate Coverage
        run: make cover

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.html

      - name: Build and Package Binaries
        run: |
          make proto
          make package VERSION=${{ github.ref_name }}

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: build/packages/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker (binary)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7,windows/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/go-captcha-service:1.0.1
            ${{ secrets.DOCKER_USERNAME }}/go-captcha-service:amd64-1.0.1
            ${{ secrets.DOCKER_USERNAME }}/go-captcha-service:arm64-1.0.1
            ${{ secrets.DOCKER_USERNAME }}/go-captcha-service:armv7-1.0.1
            ${{ secrets.DOCKER_USERNAME }}/go-captcha-service:${{ github.ref_name }}
